name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew assembleRelease --no-daemon

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Debug: List APK files
      run: find . -name "*.apk"

    - name: Upload APK to GitHub Releases
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        APK_PATH=$(find . -name "*.apk" | head -n 1)
        echo "Found APK at $APK_PATH"
        TAG_NAME="v1.0.$(date +%s)"
        RELEASE_NAME="Release $TAG_NAME"
        gh release create "$TAG_NAME" "$APK_PATH" --title "$RELEASE_NAME" --notes "Automated release from GitHub Actions"
